dist: bionic

language: python

cache:
  pip: true
  directories:
    - node_modules

addons:
  postgresql: "9.6"

python:
  - "3.6"
  # - "3.7"
  # - "3.8"

before_install:
  - psql -c 'create database olapy_web_test;' -U postgres

install:
  - pip install -U pip setuptools tox tox-travis wheel poetry

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint

script:
  - tox
