dist: xenial

language: python

cache:
  pip: true
  directories:
    - node_modules

python:
  - "2.7"
  - "3.6"
  - "3.7"

before_install:
  - psql -c 'create database olapy_web_test;' -U postgres

install:
  - pip install -U pip setuptools tox tox-travis wheel
  - export FLASK_APP=manage.py

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint

script:
  - tox
