dist: bionic

language: python

cache:
  pip: true
  directories:
    - front/node_modules

addons:
  postgresql: "9.6"

python:
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint

install:
  - pip install -U pip setuptools tox tox-travis wheel poetry

before_script:
  - psql -c 'create database olapy_web_test;' -U postgres

script:
  - tox
