"""empty message

Revision ID: faaf81e0fbcb
Revises: a083bde3649c
Create Date: 2018-03-08 11:00:07.705676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faaf81e0fbcb'
down_revision = 'a083bde3649c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cubes_dashboards',
    sa.Column('cube_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cube_id'], [u'cube.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], [u'dashboard.id'], ),
    sa.PrimaryKeyConstraint('cube_id', 'dashboard_id')
    )
    op.drop_constraint(None, 'cubes', type_='foreignkey')
    op.drop_column(u'cubes', 'dashboard_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'cubes', sa.Column('dashboard_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'cubes', 'dashboard', ['dashboard_id'], ['id'])
    op.drop_table('cubes_dashboards')
    # ### end Alembic commands ###
