
build:
	npm run build

dev:
	npm run dev

run: dev

lint:
	./node_modules/.bin/eslint --ext .js,.vue src

format:
	./node_modules/.bin/prettier --write --trailing-comma es5 \
		'src/**/*.vue' 'src/**/*.js' 'tests/**/*.js'
